name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18, 20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Type check
        run: pnpm typecheck

      - name: Lint
        run: pnpm lint

      - name: Format check
        run: pnpm format --check

      - name: Run tests
        run: pnpm test

      - name: Build for Chrome
        run: pnpm build

      - name: Build for Firefox
        run: pnpm build:firefox

      - name: Upload Chrome build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: chrome-extension-${{ matrix.node-version }}
          path: .output/chrome-mv3
          retention-days: 7

      - name: Upload Firefox build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: firefox-extension-${{ matrix.node-version }}
          path: .output/firefox-mv2
          retention-days: 7

  build-releases:
    name: Build Release Packages
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 8

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build and package for Chrome
        run: pnpm build && pnpm zip

      - name: Build and package for Firefox
        run: pnpm build:firefox && pnpm zip:firefox

      - name: Upload Chrome package
        uses: actions/upload-artifact@v4
        with:
          name: chrome-package
          path: .output/*.zip
          retention-days: 30

      - name: Upload Firefox package
        uses: actions/upload-artifact@v4
        with:
          name: firefox-package
          path: .output/*.zip
          retention-days: 30